spring:
  datasource:
    url: 'jdbc:h2:file:./filmroom-db'
    username: 'sa'
    password: 'pass'
  jpa.hibernate.ddl-auto: update
server:
  error:
    include-binding-errors: always
    include-message: always
management:
  endpoints:
    web:
      exposure:
        include=: '*'
